language: python 
python:
    - "3.5"
    - "3.6"
install:
    - pip install .
    - pip install boto3
    - pip install https://github.com/ashleygould/moto/archive/ashley.zip
    - pip install awscli
script:
    - pytest   
